"""
Alert Model
===========
Database model for alerts and notifications
"""

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from core.database import Base
import enum


class AlertType(str, enum.Enum):
    """Alert types"""
    VOICE_CLONE = "voice_clone"
    TTS_DETECTED = "tts_detected"
    AUDIO_REPLAY = "audio_replay"
    SUSPICIOUS = "suspicious"
    OTHER = "other"


class AlertPriority(str, enum.Enum):
    """Alert priority levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(str, enum.Enum):
    """Alert status"""
    PENDING = "pending"
    ACKNOWLEDGED = "acknowledged"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    ESCALATED = "escalated"


class Alert(Base):
    """
    Alerts table
    Stores all alerts generated by the system
    """
    __tablename__ = "alerts"
    
    # Primary Key
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    
    # Foreign Key to User
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    
    # Alert Info
    alert_type = Column(String(50), nullable=False)
    priority = Column(String(20), nullable=False)
    status = Column(String(20), default=AlertStatus.PENDING.value, nullable=False)
    
    # Alert Details
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    details = Column(Text, nullable=True)
    
    # Source Analysis - Foreign key to analysis_results
    analysis_id = Column(Integer, ForeignKey("analysis_results.id"), nullable=True)
    risk_score = Column(Integer, nullable=True)
    
    # Notification Status
    email_sent = Column(Boolean, default=False)
    sms_sent = Column(Boolean, default=False)
    push_sent = Column(Boolean, default=False)
    
    # Assignment
    assigned_to = Column(String(255), nullable=True)
    notes = Column(Text, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    
    # Relationships
    user = relationship("User", back_populates="alerts")
    # Note: Don't add analysis relationship to avoid circular FK
    
    def __repr__(self):
        return f"<Alert(id={self.id}, type={self.alert_type}, priority={self.priority})>"
    
    def to_dict(self):
        """Convert to dictionary"""
        return {
            "id": self.id,
            "user_id": self.user_id,
            "alert_type": self.alert_type,
            "priority": self.priority,
            "status": self.status,
            "title": self.title,
            "message": self.message,
            "details": self.details,
            "analysis_id": self.analysis_id,
            "risk_score": self.risk_score,
            "email_sent": self.email_sent,
            "sms_sent": self.sms_sent,
            "push_sent": self.push_sent,
            "assigned_to": self.assigned_to,
            "created_at": str(self.created_at) if self.created_at else None,
            "acknowledged_at": str(self.acknowledged_at) if self.acknowledged_at else None,
            "resolved_at": str(self.resolved_at) if self.resolved_at else None
        }
    
    @property
    def priority_color(self) -> str:
        """Get color for priority"""
        colors = {
            "low": "blue",
            "medium": "yellow",
            "high": "orange",
            "critical": "red"
        }
        return colors.get(self.priority, "gray")
